### ISSUE TITLE
The Reframe section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#11]
**DESKTOP**
Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48476513-880c8a00-e7ff-11e8-8657-9ab3e0facc5c.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48476543-9f4b7780-e7ff-11e8-849d-9968d946993c.png)

The current Reframe image size on the live site is too small on a large display. 

The updated set of feathered Reframe images should be used as the current site has visible edges. The Webflow website now is no longer fully interactive but uses the updated image from that latest set with feathered edges for oak: TheReframeWideFeather.png.

The background should not be the vignette style gradient but rather the image from that updated set: TheReframeWideExp.jpg

With Chrome the selected color dot keeps unsightly blue selection line:
![image](https://user-images.githubusercontent.com/22452702/48476579-bb4f1900-e7ff-11e8-94cf-fcfdfafe4b4b.png)

The styling of the color text should be the same as the Webflow site
![image](https://user-images.githubusercontent.com/22452702/48476598-c86c0800-e7ff-11e8-8c0a-f58f9892d3d3.png)

- [ ]  Replace background to TheReframeWideExp.jpg
- [x]  Implement updated set of feathered Reframe images 
- [x]  Reframe images should scale to 34% of browser width with a 600 px maximum
- [x]  Textblock should be slightly wider (See Webflow)
- [ ]  Remove  sticky blue selection line
- [x]  Section height should be 1100 px
- [ ]  Interactive color texts same as Webflow: OpenSans 17 #797979
- [x]  Colored balls slightly closer together (See Webflow)
- [x]  Space between frame image and colored balls: 62px. Live site has more.

**TABLET**
Screenshot target Webflow site on iPad Mini
![2018-11-14 11 25 00](https://user-images.githubusercontent.com/22452702/48476676-036e3b80-e800-11e8-9470-643ea3461cbf.png)

Screenshot live site on iPad Mini
![2018-11-14 11 25 12](https://user-images.githubusercontent.com/22452702/48476684-09fcb300-e800-11e8-90fa-bd9ec3e52913.png)

- [ ]  Replace background to TheReframeWideExp.jpg
- [x]  Implement updated set of feathered Reframe images 
- [x]  Reframe images 480px wide
- [x]  Textblock should be slightly wider (See Webflow)
- [x]  Section height should be 900 px
- [ ]  Interactive color texts same as Webflow: OpenSans 17 #797979
- [x]  Colored balls slightly closer together (See Webflow)

**PHONE**

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-112616](https://user-images.githubusercontent.com/22452702/48476770-39abbb00-e800-11e8-9c3e-2b20a4b905f1.png)

Screenshot live site on Nexus 5X
![screenshot_20181114-112627](https://user-images.githubusercontent.com/22452702/48476788-429c8c80-e800-11e8-857d-54593e59776c.png)

- [ ]  Replace background to TheReframeWideExp.jpg
- [x]  Implement updated set of feathered Reframe images 
- [x]  Reframe images 280px wide
- [x]  Textblock should be slightly wider for 2 lines on most phones
- [x]  Section height should be 560 px
- [ ]  Interactive color texts same as Webflow: OpenSans 16 #797979
- [x]  Colored balls slightly closer together (See Webflow)

**Comment by isaachinman** [comment]
> With Chrome the selected color dot keeps unsightly blue selection line

That's for accessibility concern, and isn't going anywhere...

**Comment by isaachinman** [comment]
> The background should not be the vignette style gradient but rather the image from that updated set: TheReframeWideExp.jpg

We already discussed this I believe? A gradient is more suitable for a background on web than a large untiled image.

**Comment by isaachinman** [comment]
> The styling of the color text should be the same as the Webflow site

Is this a genuine concern? The tooltips are working just fine.

**Comment by isaachinman** [comment]
24faa52

**Comment by Tintels** [comment]
DESKTOP

For the background please just implement solid #f4f4f4 to get rid of halos and make the separation with the previous section more clear.
Current section height is 965 rather than 1100
Making it 1100 px creates more room for the color texts. Right now the tooltips appear half overlapping with frame image
Unsightly blue selection line looks like a bug. It's necessary for what use(r) case?

Yes please replace the tooltip style with the Webflow design. FYI It was copied from https://www.roland.com/global/products/kiyola_kf-10/ (one third down)

- [ ]  Background solid #f4f4f4
- [ ]  Section height should be 1100 px
- [ ]  Space between frame image and colored balls: 62px.
- [ ]  Interactive color texts same as Webflow: OpenSans 16 #797979
- [ ]  Colored balls need to be slightly larger and move to north east to be truly centered. Problem seems to be only on desktop ..

PHONE

Sorry for the back and forth, but the text block now does not have enough padding left and right

Screenshot target Webflow site on Nexus 5X
![screenshot_20181122-235202](https://user-images.githubusercontent.com/22452702/48946647-ade80c00-ef2e-11e8-94e7-8a4d0179d48d.png)

Screenshot live site on Nexus 5X
![screenshot_20181122-235228](https://user-images.githubusercontent.com/22452702/48946637-a58fd100-ef2e-11e8-94f2-179ce28ec849.png)

Frame image is too large

- [ ]  Decrease width of text block a bit. Can you make the copy line break between "of' and "shaped" on most / your phone?
- [ ]  Reframe images 280px wide

**Comment by isaachinman** [comment]
> Colored balls need to be slightly larger and move to north east to be truly centered. Problem seems to be only on desktop ..

Provide a different image then. They are centered on the page - the image is not due to the shadow offset.

**Comment by isaachinman** [comment]
b0273ac
