### ISSUE TITLE
Meta content entry for usability and SEO

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#4]
Pllease implement this list of page titles that I created earlier. 

HOME
Page name
Wundershine - Smart Picture Framing
Wundershine - Slimme wissellijsten

Slug
-

APP
Page name
Wundershine App - Wundershine
Wundershine App - Wundershine

Slug
app
(this will be more consumer familiar than native-app. For web app later we can do web-app)

CREATIVE
Create you own art - Wundershine
Maak je eigen kunst - Wundershine

Slug
creative

ABOUT
About us - Wundershine
Over ons - Wundershine

Slug
about

SHOP
Wundershine Shop - Wundershine
Wundershine Shop - Wundershine

Slug
shop.wundershine.com

I just entered the meta description below into our Shopify storefront. We can also use that for our homepage:

Wundershine makes it extremely easy to get a feed of fresh pictures and digital art from your smartphone or camera to the walls of your home. Display your photos in high quality, stylish picture frames in solid oak, solid walnut, black or white finish.

Het Wundershine systeem maakt het super makkelijk om altijd leuke, recente foto's mooi ingelijst aan de muur te hebben - direct van je mobiele telefoon. Laat je foto's zien in stijlvolle houten wissellijsten van massief eiken, walnoot, wit of zwart.

Not sure yet if we should / need to have a custom meta description for our other pages. I will research that later.

**Comment by Tintels** [comment]
CHECKLIST

- [ ] Page titles / slug English
- [ ] Page titles Dutch
- [ ] Meta description homepage English
- [ ] Meta description homepage Dutch

**Comment by isaachinman** [comment]
> Not sure yet if we should / need to have a custom meta description for our other pages. I will research that later.

Yes, I believe we should. Not terribly important for now.

**Comment by isaachinman** [comment]
da435a5
